#!/usr/bin/env bash

# Block if the MLSA was not accepted
if ! [[ "${1}" == "true" || "${1}" == "1" ]] ; then
  cat <<EOF
=========================================================================

Use of this Software is subject to the terms of the Chef Online Master
License and Services Agreement. You can find the latest copy of the
agreement here:

https://www.chef.io/online-master-agreement

=========================================================================
EOF

  # TO INFINITY AND BEYOND!
  while true
  do
    sleep 5
  done
fi
