# Slack channel in Chef Software slack to send notifications about build failures, etc
project:
  alias: mlsa

slack:
  notify_channel:
    - releng-notify


habitat_packages:
  - mlsa

github:
  delete_branch_on_merge: true
  minor_bump_labels:
     - "Version: Bump Minor"

promote:
  actions:
    - built_in:promote_habitat_packages

merge_actions:
  - built_in:trigger_habitat_package_build
