# Slack channel in Chef Software slack to send notifications about build failures, etc
project:
  alias: mlsa

slack:
  notify_channel:
    - releng-notify

pipelines:
  - habitat/build

github:
  delete_branch_on_merge: true
  minor_bump_labels:
     - "Version: Bump Minor"

subscriptions:
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - trigger_pipeline:habitat/build
